### ISSUE TITLE
ruadlist easylist doesn't work

### ISSUE THREAD

**Issue by nightuser** [Plaque-fcc/luakit-adblock#2]
easylist.txt works fine, but when I'm enabling ruadlist+easylist.txt ( https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt ), luakit just shows blank white pages on all sites

**Comment by Plaque-fcc** [comment]
1. Everything that works with the original AdBlock should be considered working.
2. Thank you for pointing out your case; I'd be delighted having a debug session on it, gimme some time tonight.

**Comment by Plaque-fcc** [comment]
`Line '*$third-party,subdocument,domain=ints.ifolder.ru' brought us a .* pattern!`

This is a blocking pattern, thus the problem of blocking-all trouble lies right there.
The bug is known to us, and the original adblock.lua developer was informed of its existence. Moreover, someday I'll take my time and remaster the regex adapter function here.

И — да, знаю, что костыльно немного, но пока работает так.

Now ready to be tested out again, and if it got fixed, please, close this issue as soon as you can confirm that.

**Comment by nightuser** [comment]
Seems to work. Thanks!

**Comment by Plaque-fcc** [comment]
Thank you.
And keep your own rules apart from your subscriptions, i.e. use file user-custom.txt to hold them.

**Comment by fangelion** [comment]
in function abp_to_pattern you a lost variable opt that contains all the parameters found after the $ symbol and sends only the first line, which often contains only a URL site that is blocked

в функции abp_to_pattern вы теряете переменную opt которая содержит все параметры найденые после символа $ и передает только первую строку, которая часто содержит только URL сайта, который полностью блокируется

**Comment by Plaque-fcc** [comment]
May be it. It was not my part, so I need to redesign it anyways. Thank you for your notice, it is important to me.

В смысле, спасибо, принято. Переделывать всё равно потребуется, ибо не моё.

**Comment by fangelion** [comment]
я луа плохо знаю, давно его в простейшей форме юзал. щас если гайд поможет вспомнить что там и как можно, то накомичу исправление. Я питонист вообще

**Comment by Plaque-fcc** [comment]
А я вообще Python знаю через левое плечо передней пяткой, а Lua не знаю
совсем… Просто, нравится luakit, хоть убей.

 Если сможешь поправить целиком либо полностью, будет супер.

**Comment by Plaque-fcc** [comment]
Слышь, питонист? Нет желания покодить учётную программу на замену 1C и прочим проприетарщинам? ;D

**Comment by Plaque-fcc** [comment]
Кстати, исправление сразу же уйдёт в https://github.com/mason-larobina/luakit-plugins/
Если есть мысли, какие модули стоит туда добавить, не стесняйся; или что реализовать в виде модулей. Пока там лишь adblock да user agent switcher, ибо это пока всё, что мне требовалось.
